CREATE TABLE chat (
    chatId INT PRIMARY KEY NOT NULL,
    userId INT NOT NULL,
    stateNum INT NOT NULL,
    chatContent VARCHAR(500) NOT NULL,
    inputTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES user(userId)
);